const esbuild = require("esbuild");
const builtins = require("module").builtinModules;
const fs = require("fs");
const path = require("path");

const distDir = path.join(__dirname, "dist");
if (!fs.existsSync(distDir)) fs.mkdirSync(distDir);
const srcDir = path.join(__dirname, "src");

// ─── Generate curated-themes module ─────────────────────────────────────────
// The 34 curated themes are bundled into main.js as a { name: cssBlock } map
// rather than concatenated into styles.css. Only the active theme's block is
// injected into the DOM at runtime (core/design-system), so the style engine
// never parses 33 unused [data-theme] blocks at load.
const yaml = require("js-yaml");
const sass = require("sass");

// Use local packages directory if we are in the monorepo workspace, otherwise fall back to node_modules
let themesDir = path.resolve(__dirname, "../../packages/themes");
if (!fs.existsSync(themesDir)) {
  themesDir = path.join(__dirname, "node_modules", "@stnd", "themes");
}

const themes = {};
if (fs.existsSync(themesDir)) {
  const dirs = fs.readdirSync(themesDir).filter(d => {
    return fs.existsSync(path.join(themesDir, d, "tokens.yaml"));
  }).sort();

  for (const dir of dirs) {
    const themeName = dir;
    const tokensPath = path.join(themesDir, dir, "tokens.yaml");
    const scssPath = path.join(themesDir, dir, `${dir}.scss`);

    try {
      const doc = yaml.load(fs.readFileSync(tokensPath, "utf8"));
      const tokens = doc.tokens || {};
      const decls = Object.entries(tokens)
        .map(([k, v]) => `  --${k}: ${v};`)
        .join("\n");

      let scssContent = "";
      if (fs.existsSync(scssPath)) {
        scssContent = fs.readFileSync(scssPath, "utf8");
        // Strip anything inside TOKENS.YAML ADAPTER comments
        scssContent = scssContent.replace(/\/\* TOKENS\.YAML ADAPTER BEGIN \*\/[\s\S]*?\/\* TOKENS\.YAML ADAPTER END \*\//g, "").trim();
        // Strip any @use statements
        scssContent = scssContent.replace(/@use\s+['"][^'"]+['"]\s*;?/g, "");
        // Normalize theme selector to parent selector &
        scssContent = scssContent.replace(new RegExp(`:root\\[data-theme=["']?${themeName}["']?\\]`, "g"), "&");
        scssContent = scssContent.replace(new RegExp(`\\[data-theme=["']?${themeName}["']?\\]`, "g"), "&");
      }

      const wrappedThemeScss = `body.stnd-adapter[data-stnd-theme="${themeName}"] {\n${decls}\n\n${scssContent}\n}`;
      
      const compiled = sass.compileString(wrappedThemeScss, { style: "expanded" });
      themes[themeName] = compiled.css;
    } catch (e) {
      console.error(`Failed to compile theme "${themeName}":`, e);
    }
  }
}

fs.writeFileSync(
  path.join(srcDir, "themes.generated.js"),
  "// AUTO-GENERATED by build.js — do not edit.\n" +
    "// Curated theme token blocks, bundled into main.js and injected on demand\n" +
    "// by core/design-system (only the active [data-theme] block is ever in the DOM).\n" +
    "module.exports = " +
    JSON.stringify(themes) +
    ";\n",
);
const themeCount = Object.keys(themes).length;
console.log(`Generated themes.generated.js (${themeCount} themes)`);

// ─── Generate curated-fonts module ──────────────────────────────────────────
// Scans for typefaces inside packages/fonts/ and bundles their CSS `@font-face`
// declarations into src/fonts.generated.js (using placeholder paths).
// Copies the corresponding binary `.woff2` files to dist/fonts/.
let fontsDir = path.resolve(__dirname, "../../packages/fonts");
if (!fs.existsSync(fontsDir)) {
  fontsDir = path.join(__dirname, "node_modules", "@stnd", "fonts");
}

const distFontsDir = path.join(distDir, "fonts");
if (!fs.existsSync(distFontsDir)) {
  fs.mkdirSync(distFontsDir, { recursive: true });
}

const sanitizeFontFileName = (name) =>
  String(name)
    .replace(/\[/g, "-")
    .replace(/\]/g, "-")
    .replace(/,/g, "-");

let combinedFontsCss = "";
if (fs.existsSync(fontsDir)) {
  const fontDirs = fs.readdirSync(fontsDir).filter(d => {
    return fs.lstatSync(path.join(fontsDir, d)).isDirectory() &&
           d !== "node_modules" && d !== "tools";
  }).sort();

  for (const dir of fontDirs) {
    const cssPath = path.join(fontsDir, dir, `${dir}.css`);
    const binaryFontsDir = path.join(fontsDir, dir, "fonts");

    if (fs.existsSync(cssPath)) {
      let cssContent = fs.readFileSync(cssPath, "utf8");
      
      // Replace relative paths in url() with placeholder STND_FONT_URL:<filename>
      const urlRegex = /url\(['"]?(?:\.\/)?fonts\/(.*?)['"]?\)/g;
      cssContent = cssContent.replace(urlRegex, (match, fontName) => {
        const safeName = sanitizeFontFileName(fontName);
        return `url("STND_FONT_URL:${safeName}")`;
      });
      
      combinedFontsCss += `/* --- Font: ${dir} --- */\n` + cssContent + "\n\n";
    }

    if (fs.existsSync(binaryFontsDir)) {
      const binaries = fs.readdirSync(binaryFontsDir);
      for (const binary of binaries) {
        if (binary.endsWith(".woff2") || binary.endsWith(".otf") || binary.endsWith(".ttf")) {
          const safeBinaryName = sanitizeFontFileName(binary);
          fs.copyFileSync(
            path.join(binaryFontsDir, binary),
            path.join(distFontsDir, safeBinaryName),
          );
        }
      }
    }
  }
}

fs.writeFileSync(
  path.join(srcDir, "fonts.generated.js"),
  "// AUTO-GENERATED by build.js — do not edit.\n" +
    "// Combined font-face stylesheet with path placeholders, loaded at startup\n" +
    "// and dynamically resolved to local assets by core/design-system.\n" +
    "module.exports = " +
    JSON.stringify(combinedFontsCss) +
    ";\n",
);
console.log("Generated fonts.generated.js and copied binary fonts");

// ─── Bundle JS ───────────────────────────────────────────────────────────────
esbuild
  .build({
    entryPoints: ["main.js"],
    bundle: true,
    platform: "browser",
    outfile: "dist/main.js",
    external: [
      "obsidian",
      "electron",
      "@electron/remote",
      "@codemirror/autocomplete",
      "@codemirror/collab",
      "@codemirror/commands",
      "@codemirror/language",
      "@codemirror/lint",
      "@codemirror/search",
      "@codemirror/state",
      "@codemirror/view",
      "@lezer/common",
      "@lezer/highlight",
      "@lezer/lr",
      ...builtins,
    ],
    format: "cjs",
    target: "es2020",
    minify: true,
  })
  .then(async () => {
    console.log("Built dist/main.js");

    // ─── Bundle CSS ───────────────────────────────────────────────────────────
    // Base + feature CSS only. Curated themes are bundled into main.js (above).
    const filesToCombine = [
      "base.css",
      "design-system.css",
      "panel.css",
      "image.css",
      "snippets.css",
    ];

    let combinedCss = "";
    
    // Inject standard CSS first
    let standardCssPath = path.resolve(__dirname, "../../packages/styles/dist/obsidian.css");
    if (!fs.existsSync(standardCssPath)) {
      standardCssPath = path.join(__dirname, "node_modules", "@stnd", "styles", "dist", "obsidian.css");
    }
    if (fs.existsSync(standardCssPath)) {
        combinedCss += "/* --- @stnd/styles (Obsidian Core) --- */\n";
        combinedCss += fs.readFileSync(standardCssPath, "utf8") + "\n\n";
    } else {
        console.warn("Warning: @stnd/styles/dist/obsidian.css not found. Did you run pnpm install or build @stnd/styles?");
    }

    for (const file of filesToCombine) {
      const filePath = path.join(srcDir, file);
      if (fs.existsSync(filePath)) {
        combinedCss += fs.readFileSync(filePath, "utf8") + "\n\n";
      } else {
        console.warn(`Warning: ${file} not found in src/`);
      }
    }

    // Feature CSS
    const featuresDir = path.join(srcDir, "features");
    if (fs.existsSync(featuresDir)) {
      for (const feature of fs.readdirSync(featuresDir).sort()) {
        const cssFile = path.join(featuresDir, feature, "styles.css");
        if (fs.existsSync(cssFile)) {
          combinedCss += `/* --- Feature: ${feature} --- */\n`;
          combinedCss += fs.readFileSync(cssFile, "utf8") + "\n\n";
        }
      }
    }

    const sass = require("sass");

    let scssSource = combinedCss;
    scssSource = scssSource.replace(/^\uFEFF/gm, ""); // Remove BOM
    
    // Extract text-box-trim rules (mostly from @stnd/styles) and wrap them in .stnd-text-trim
    const trimRuleRegex = /[^}]+?\{[^{}]*text-box-trim[^{}]+\}/g;
    let trimRuleMatch = scssSource.match(trimRuleRegex);
    if (trimRuleMatch) {
        scssSource = scssSource.replace(trimRuleRegex, "");
        const cleanedTrimRules = trimRuleMatch.map(rule => rule.replace(/\b(?:td|th),/g, ''));
        scssSource += `\n\n&.stnd-text-trim :is(.markdown-preview-view, .markdown-rendered) {\n  ${cleanedTrimRules.join('\n  ')}\n}\n`;
    }

    scssSource = scssSource.replace(/:root/g, "&"); // Scope CSS variables
    scssSource = scssSource.replace(/body[\w:.\-()]*\.stnd-adapter/g, (match) => {
        return "&" + match.replace(/^body/, '').replace(/\.stnd-adapter/, '');
    });
    scssSource = scssSource.replace(/(?<![-_a-zA-Z0-9])body\b/g, "&");
    scssSource = scssSource.replace(/(?:^|\s|,)\.stnd-adapter([\w:.\-()]*)/g, (match, p1) => {
        const prefix = match.match(/^[ \s,]+/);
        const prefStr = prefix ? prefix[0] : "";
        return prefStr + "&" + p1;
    });

    const wrappedScss = `body.stnd-adapter {\n${scssSource}\n}`;

    let minifiedCss;
    try {
      const compiled = sass.compileString(wrappedScss, { style: "compressed" });
      minifiedCss = compiled.css;

      // Concaténer directement fonts.css pour éviter la lenteur de compilation SASS
      if (fs.existsSync(featuresDir)) {
        for (const feature of fs.readdirSync(featuresDir).sort()) {
          const fontsFile = path.join(featuresDir, feature, "fonts.css");
          if (fs.existsSync(fontsFile)) {
            minifiedCss += "\n" + fs.readFileSync(fontsFile, "utf8");
          }
        }
      }
    } catch (e) {
      console.error("SASS compilation failed:", e);
      process.exit(1);
    }

    fs.writeFileSync(path.join(distDir, "styles.css"), minifiedCss);
    console.log(
      `Built dist/styles.css (${(minifiedCss.length / 1024) | 0}KB minified, themes lazy-loaded)`,
    );

    // ─── Deploy into the Obsidian vault ──────────────────────────────────────
    const vaultPlugins =
      process.env.VAULT_PLUGINS ||
      path.join(
        require("os").homedir(),
        "Documents",
        "Atelier",
        ".obsidian",
        "plugins",
      );
    const dest = path.join(vaultPlugins, "garden");
    if (fs.existsSync(vaultPlugins)) {
      if (!fs.existsSync(dest)) fs.mkdirSync(dest);
      fs.copyFileSync(
        path.join(distDir, "main.js"),
        path.join(dest, "main.js"),
      );
      fs.copyFileSync(
        path.join(distDir, "styles.css"),
        path.join(dest, "styles.css"),
      );
      fs.copyFileSync(
        path.join(__dirname, "manifest.json"),
        path.join(dest, "manifest.json"),
      );

      // Copy fonts recursively
      const copyDirSync = (src, target) => {
        if (!fs.existsSync(target)) fs.mkdirSync(target, { recursive: true });
        const entries = fs.readdirSync(src, { withFileTypes: true });
        for (const entry of entries) {
          const srcPath = path.join(src, entry.name);
          const destPath = path.join(target, entry.name);
          if (entry.isDirectory()) {
            copyDirSync(srcPath, destPath);
          } else {
            fs.copyFileSync(srcPath, destPath);
          }
        }
      };

      const distFonts = path.join(distDir, "fonts");
      if (fs.existsSync(distFonts)) {
        copyDirSync(distFonts, path.join(dest, "fonts"));
      }

      console.log(`Deployed to vault: ${dest}`);
    } else {
      console.log(
        "Vault not found — skipped deploy (set VAULT_PLUGINS to enable).",
      );
    }
  })
  .catch(() => process.exit(1));
