const esbuild = require("esbuild");
const builtins = require("module").builtinModules;
const fs = require("fs");
const path = require("path");

const distDir = path.join(__dirname, "dist");
if (!fs.existsSync(distDir)) fs.mkdirSync(distDir);
const srcDir = path.join(__dirname, "src");

// ─── Generate curated-themes module ─────────────────────────────────────────
// The 34 curated themes are bundled into main.js as a { name: cssBlock } map
// rather than concatenated into styles.css. Only the active theme's block is
// injected into the DOM at runtime (core/design-system), so the style engine
// never parses 33 unused [data-theme] blocks at load.
const themesDir = path.join(__dirname, "node_modules", "@stnd", "themes");
const themes = {};
if (fs.existsSync(themesDir)) {
  for (const dir of fs.readdirSync(themesDir).sort()) {
    const f = path.join(themesDir, dir, "_tokens.generated.scss");
    if (fs.existsSync(f)) themes[dir] = fs.readFileSync(f, "utf8");
  }
}
fs.writeFileSync(
  path.join(srcDir, "themes.generated.js"),
  "// AUTO-GENERATED by build.js — do not edit.\n" +
    "// Curated theme token blocks, bundled into main.js and injected on demand\n" +
    "// by core/design-system (only the active [data-theme] block is ever in the DOM).\n" +
    "module.exports = " +
    JSON.stringify(themes) +
    ";\n",
);
const themeCount = Object.keys(themes).length;
console.log(`Generated themes.generated.js (${themeCount} themes)`);

// ─── Bundle JS ───────────────────────────────────────────────────────────────
esbuild
  .build({
    entryPoints: ["main.js"],
    bundle: true,
    platform: "browser",
    outfile: "dist/main.js",
    external: [
      "obsidian",
      "electron",
      "@electron/remote",
      "@codemirror/autocomplete",
      "@codemirror/collab",
      "@codemirror/commands",
      "@codemirror/language",
      "@codemirror/lint",
      "@codemirror/search",
      "@codemirror/state",
      "@codemirror/view",
      "@lezer/common",
      "@lezer/highlight",
      "@lezer/lr",
      ...builtins,
    ],
    format: "cjs",
    target: "es2020",
    minify: true,
  })
  .then(async () => {
    console.log("Built dist/main.js");

    // ─── Bundle CSS ───────────────────────────────────────────────────────────
    // Base + feature CSS only. Curated themes are bundled into main.js (above).
    const filesToCombine = [
      "base.css",
      "design-system.css",
      "panel.css",
      "image.css",
      "snippets.css",
    ];

    let combinedCss = "";
    
    // Inject standard CSS first
    const standardCssPath = path.join(__dirname, "node_modules", "@stnd", "styles", "dist", "obsidian.css");
    if (fs.existsSync(standardCssPath)) {
        combinedCss += "/* --- @stnd/styles (Obsidian Core) --- */\n";
        combinedCss += fs.readFileSync(standardCssPath, "utf8") + "\n\n";
    } else {
        console.warn("Warning: @stnd/styles/dist/obsidian.css not found. Did you run pnpm install?");
    }

    for (const file of filesToCombine) {
      const filePath = path.join(srcDir, file);
      if (fs.existsSync(filePath)) {
        combinedCss += fs.readFileSync(filePath, "utf8") + "\n\n";
      } else {
        console.warn(`Warning: ${file} not found in src/`);
      }
    }

    // Feature CSS
    const featuresDir = path.join(srcDir, "features");
    if (fs.existsSync(featuresDir)) {
      for (const feature of fs.readdirSync(featuresDir).sort()) {
        const cssFile = path.join(featuresDir, feature, "styles.css");
        if (fs.existsSync(cssFile)) {
          combinedCss += `/* --- Feature: ${feature} --- */\n`;
          combinedCss += fs.readFileSync(cssFile, "utf8") + "\n\n";
        }
      }
    }

    const sass = require("sass");

    let scssSource = combinedCss;
    scssSource = scssSource.replace(/^\uFEFF/gm, ""); // Remove BOM
    
    // Extract text-box-trim rules (mostly from @stnd/styles) and wrap them in .stnd-text-trim
    const trimRuleRegex = /[^}]+?\{[^{}]*text-box-trim[^{}]+\}/g;
    let trimRuleMatch = scssSource.match(trimRuleRegex);
    if (trimRuleMatch) {
        scssSource = scssSource.replace(trimRuleRegex, "");
        const cleanedTrimRules = trimRuleMatch.map(rule => rule.replace(/\b(?:td|th),/g, ''));
        scssSource += `\n\n&.stnd-text-trim {\n  ${cleanedTrimRules.join('\n  ')}\n}\n`;
    }

    scssSource = scssSource.replace(/:root/g, "&"); // Scope CSS variables
    scssSource = scssSource.replace(/body[\w:.\-()]*\.stnd-adapter/g, (match) => {
        return "&" + match.replace(/^body/, '').replace(/\.stnd-adapter/, '');
    });
    scssSource = scssSource.replace(/(?:^|\s|,)\.stnd-adapter([\w:.\-()]*)/g, (match, p1) => {
        const prefix = match.match(/^[ \s,]+/);
        const prefStr = prefix ? prefix[0] : "";
        return prefStr + "&" + p1;
    });

    const wrappedScss = `body.stnd-adapter {\n${scssSource}\n}`;

    let minifiedCss;
    try {
      const compiled = sass.compileString(wrappedScss, { style: "compressed" });
      minifiedCss = compiled.css;
    } catch (e) {
      console.error("SASS compilation failed:", e);
      process.exit(1);
    }

    fs.writeFileSync(path.join(distDir, "styles.css"), minifiedCss);
    console.log(
      `Built dist/styles.css (${(minifiedCss.length / 1024) | 0}KB minified, themes lazy-loaded)`,
    );

    // ─── Deploy into the Obsidian vault ──────────────────────────────────────
    const vaultPlugins =
      process.env.VAULT_PLUGINS ||
      path.join(
        require("os").homedir(),
        "Documents",
        "Atelier",
        ".obsidian",
        "plugins",
      );
    const dest = path.join(vaultPlugins, "garden");
    if (fs.existsSync(vaultPlugins)) {
      if (!fs.existsSync(dest)) fs.mkdirSync(dest);
      fs.copyFileSync(
        path.join(distDir, "main.js"),
        path.join(dest, "main.js"),
      );
      fs.copyFileSync(
        path.join(distDir, "styles.css"),
        path.join(dest, "styles.css"),
      );
      fs.copyFileSync(
        path.join(__dirname, "manifest.json"),
        path.join(dest, "manifest.json"),
      );

      console.log(`Deployed to vault: ${dest}`);
    } else {
      console.log(
        "Vault not found — skipped deploy (set VAULT_PLUGINS to enable).",
      );
    }
  })
  .catch(() => process.exit(1));
