const esbuild = require("esbuild");
const builtins = require("module").builtinModules;
const fs = require("fs");
const path = require("path");

const distDir = path.join(__dirname, "dist");
if (!fs.existsSync(distDir)) fs.mkdirSync(distDir);
const srcDir = path.join(__dirname, "src");

// ─── Generate curated-themes module ─────────────────────────────────────────
// The 34 curated themes are bundled into main.js as a { name: cssBlock } map
// rather than concatenated into styles.css. Only the active theme's block is
// injected into the DOM at runtime (core/design-system), so the style engine
// never parses 33 unused [data-theme] blocks at load.
const yaml = require("yaml");
const sass = require("sass");

let mapWebSelectorsToObsidian = (css) => css;
try {
  const mapPath = path.resolve(__dirname, "../../packages/themes/_scripts/utils/selector-map.cjs");
  if (fs.existsSync(mapPath)) {
    mapWebSelectorsToObsidian = require(mapPath).mapWebSelectorsToObsidian;
  }
} catch (e) {
  console.warn("Could not load selector-map utility:", e.message);
}

// Use local packages directory if we are in the monorepo workspace, otherwise fall back to node_modules
let themesDir = path.resolve(__dirname, "../../packages/themes");
if (!fs.existsSync(themesDir)) {
  themesDir = path.join(__dirname, "node_modules", "@stnd", "themes");
}

const themes = {};
if (fs.existsSync(themesDir)) {
  const dirs = fs.readdirSync(themesDir).filter(d => {
    return fs.existsSync(path.join(themesDir, d, "tokens.yaml"));
  }).sort();

  for (const dir of dirs) {
    const themeName = dir;
    const tokensPath = path.join(themesDir, dir, "tokens.yaml");
    const scssPath = path.join(themesDir, dir, `${dir}.scss`);

    try {
      const doc = yaml.parse(fs.readFileSync(tokensPath, "utf8"));
      const tokens = doc.tokens || {};
      const decls = Object.entries(tokens)
        .map(([k, v]) => `  --${k}: ${v};`)
        .join("\n");

      let scssContent = "";
      if (fs.existsSync(scssPath)) {
        scssContent = fs.readFileSync(scssPath, "utf8");
        // Strip anything inside TOKENS.YAML ADAPTER comments
        scssContent = scssContent.replace(/\/\* TOKENS\.YAML ADAPTER BEGIN \*\/[\s\S]*?\/\* TOKENS\.YAML ADAPTER END \*\//g, "").trim();
        // Strip any @use statements
        scssContent = scssContent.replace(/@use\s+['"][^'"]+['"]\s*;?/g, "");
        // Normalize theme selector to parent selector &
        scssContent = scssContent.replace(new RegExp(`:root\\[data-theme=["']?${themeName}["']?\\],?\\s*`, "g"), "");
        scssContent = scssContent.replace(new RegExp(`\\[data-theme=["']?${themeName}["']?\\]`, "g"), "&");
        // Remap standard web selectors to Obsidian dual selectors
        scssContent = mapWebSelectorsToObsidian(scssContent);
      }

      const wrappedThemeScss = `body.stnd-adapter[data-stnd-theme="${themeName}"] {\n${decls}\n\n${scssContent}\n}`;
      
      const compiled = sass.compileString(wrappedThemeScss, { style: "expanded" });
      themes[themeName] = compiled.css;
    } catch (e) {
      console.error(`Failed to compile theme "${themeName}":`, e);
    }
  }
}

fs.writeFileSync(
  path.join(srcDir, "themes.generated.js"),
  "// AUTO-GENERATED by build.js — do not edit.\n" +
    "// Curated theme token blocks, bundled into main.js and injected on demand\n" +
    "// by core/design-system (only the active [data-theme] block is ever in the DOM).\n" +
    "module.exports = " +
    JSON.stringify(themes) +
    ";\n",
);
const themeCount = Object.keys(themes).length;
console.log(`Generated themes.generated.js (${themeCount} themes)`);

// ─── Generate curated-fonts module ──────────────────────────────────────────
// Scans for typefaces inside packages/fonts/ and bundles their CSS `@font-face`
// declarations into src/fonts.generated.js (using placeholder paths).
// Copies the corresponding binary `.woff2` files to dist/fonts/.
let fontsDir = path.resolve(__dirname, "../../packages/fonts");
if (!fs.existsSync(fontsDir)) {
  fontsDir = path.join(__dirname, "node_modules", "@stnd", "fonts");
}

const distFontsDir = path.join(distDir, "fonts");
if (!fs.existsSync(distFontsDir)) {
  fs.mkdirSync(distFontsDir, { recursive: true });
}

const sanitizeFontFileName = (name) =>
  String(name)
    .replace(/\[/g, "-")
    .replace(/\]/g, "-")
    .replace(/,/g, "-");

let combinedFontsCss = "";
if (fs.existsSync(fontsDir)) {
  const fontDirs = fs.readdirSync(fontsDir).filter(d => {
    return fs.lstatSync(path.join(fontsDir, d)).isDirectory() &&
           d !== "node_modules" && d !== "tools";
  }).sort();

  for (const dir of fontDirs) {
    const cssPath = path.join(fontsDir, dir, `${dir}.css`);
    const binaryFontsDir = path.join(fontsDir, dir, "fonts");

    if (fs.existsSync(cssPath)) {
      let cssContent = fs.readFileSync(cssPath, "utf8");
      
      // Replace relative paths in url() with placeholder STND_FONT_URL:<filename>
      const urlRegex = /url\(['"]?(?:\.\/)?fonts\/(.*?)['"]?\)/g;
      cssContent = cssContent.replace(urlRegex, (match, fontName) => {
        const safeName = sanitizeFontFileName(fontName);
        return `url("STND_FONT_URL:${safeName}")`;
      });
      
      combinedFontsCss += `/* --- Font: ${dir} --- */\n` + cssContent + "\n\n";
    }

    if (fs.existsSync(binaryFontsDir)) {
      const binaries = fs.readdirSync(binaryFontsDir);
      for (const binary of binaries) {
        if (binary.endsWith(".woff2") || binary.endsWith(".otf") || binary.endsWith(".ttf")) {
          const safeBinaryName = sanitizeFontFileName(binary);
          fs.copyFileSync(
            path.join(binaryFontsDir, binary),
            path.join(distFontsDir, safeBinaryName),
          );
        }
      }
    }
  }
}

fs.writeFileSync(
  path.join(srcDir, "fonts.generated.js"),
  "// AUTO-GENERATED by build.js — do not edit.\n" +
    "// Combined font-face stylesheet with path placeholders, loaded at startup\n" +
    "// and dynamically resolved to local assets by core/design-system.\n" +
    "module.exports = " +
    JSON.stringify(combinedFontsCss) +
    ";\n",
);
console.log("Generated fonts.generated.js and copied binary fonts");

// ─── Bundle JS ───────────────────────────────────────────────────────────────
esbuild
  .build({
    entryPoints: [path.join(__dirname, "main.js")],
    bundle: true,
    platform: "browser",
    outfile: path.join(distDir, "main.js"),
    external: [
      "obsidian",
      "electron",
      "@electron/remote",
      "@codemirror/autocomplete",
      "@codemirror/collab",
      "@codemirror/commands",
      "@codemirror/language",
      "@codemirror/lint",
      "@codemirror/search",
      "@codemirror/state",
      "@codemirror/view",
      "@lezer/common",
      "@lezer/highlight",
      "@lezer/lr",
      ...builtins,
    ],
    format: "cjs",
    target: "es2020",
    minify: true,
  })
  .then(async () => {
    console.log("Built dist/main.js");

    // ─── Bundle CSS ───────────────────────────────────────────────────────────
    // Framework core + feature CSS. Curated themes are bundled into main.js (above).
    let combinedCss = "";
    
    // 1. Inject standard CSS first
    let standardCssPath = path.resolve(__dirname, "../../packages/styles/dist/obsidian.css");
    if (!fs.existsSync(standardCssPath)) {
      standardCssPath = path.join(__dirname, "node_modules", "@stnd", "styles", "dist", "obsidian.css");
    }
    if (fs.existsSync(standardCssPath)) {
        combinedCss += "/* --- @stnd/styles (Obsidian Core) --- */\n";
        combinedCss += fs.readFileSync(standardCssPath, "utf8") + "\n\n";
    } else {
        const scssFallback = path.join(__dirname, "node_modules", "@stnd", "styles", "obsidian.scss");
        if (fs.existsSync(scssFallback)) {
          const sass = require("sass");
          const compiled = sass.compile(scssFallback, { loadPaths: [path.dirname(scssFallback)] });
          combinedCss += "/* --- @stnd/styles (Obsidian Core) --- */\n";
          combinedCss += compiled.css + "\n\n";
        } else {
          console.warn("Warning: @stnd/styles/dist/obsidian.css not found. Did you run pnpm install or build @stnd/styles?");
        }
    }

    const featuresDir = path.join(srcDir, "features");

    // 2. Inject Design System adapter styles next
    const dsCssPath = path.join(featuresDir, "design-system", "styles.css");
    if (fs.existsSync(dsCssPath)) {
      combinedCss += "/* --- Feature: design-system (Adapter) --- */\n";
      combinedCss += fs.readFileSync(dsCssPath, "utf8") + "\n\n";
    } else {
      console.warn("Warning: design-system/styles.css not found.");
    }

    // 3. Inject all other feature styles in deterministic order.
    //
    // The plugin's own UI (panel, status icon and menu, settings, feed,
    // mycelium) is collected apart as well: the whole bundle below is wrapped
    // in `body.stnd-adapter`, a class that only exists while the design system
    // ("artisan mode") is on. Someone who has it off must still get a working,
    // coloured sprout and a styled panel, so these files — which use Obsidian's
    // own variables only — are emitted a second time for `body:not(.stnd-adapter)`.
    const UI_FEATURES = ["feed", "mycelium", "panel", "publish-status", "settings"];
    let uiCss = "";
    if (fs.existsSync(featuresDir)) {
      for (const feature of fs.readdirSync(featuresDir).sort()) {
        if (feature === "design-system") continue; // already injected first
        const cssFile = path.join(featuresDir, feature, "styles.css");
        if (fs.existsSync(cssFile)) {
          const css = fs.readFileSync(cssFile, "utf8");
          combinedCss += `/* --- Feature: ${feature} --- */\n`;
          combinedCss += css + "\n\n";
          if (UI_FEATURES.includes(feature)) uiCss += css + "\n\n";
        }
      }
    }

    const sass = require("sass");

    let scssSource = combinedCss;
    scssSource = scssSource.replace(/^\uFEFF/gm, ""); // Remove BOM
    
    // Extract text-box-trim rules (mostly from @stnd/styles) and wrap them in .stnd-text-trim
    const trimRuleRegex = /[^}]+?\{[^{}]*text-box-trim[^{}]+\}/g;
    // @stnd/styles already wraps its text-box-trim rules in an @supports block.
    // Take those blocks out whole (balanced braces) first: the regex below only
    // knows bare rules, and run on an @supports block it ate the header and the
    // first rule and left a stray "}" that closed the body.stnd-adapter wrapper
    // early, so every token after that point lost its scope.
    const supportsTrim = /@supports\s*\(\s*text-box-trim[^)]*\)\s*\{/g;
    const trimBlocks = [];
    for (let m; (m = supportsTrim.exec(scssSource)); ) {
      let depth = 1, i = m.index + m[0].length;
      for (; i < scssSource.length && depth > 0; i++) {
        if (scssSource[i] === "{") depth++;
        else if (scssSource[i] === "}") depth--;
      }
      trimBlocks.push(scssSource.slice(m.index + m[0].length, i - 1));
      scssSource = scssSource.slice(0, m.index) + scssSource.slice(i);
      supportsTrim.lastIndex = m.index;
    }
    let trimRuleMatch = scssSource.match(trimRuleRegex) || [];
    if (trimBlocks.length) trimRuleMatch = trimRuleMatch.concat(trimBlocks);
    if (trimRuleMatch.length) {
        scssSource = scssSource.replace(trimRuleRegex, "");
        const cleanedTrimRules = trimRuleMatch.map(rule => rule.replace(/\b(?:td|th),/g, ''));
        scssSource += `\n\n@supports (text-box-trim: trim-both) {\n  &.stnd-text-trim :is(.markdown-preview-view, .markdown-rendered) {\n    ${cleanedTrimRules.join('\n    ')}\n  }\n}\n`;
    }

    scssSource = scssSource.replace(/:root/g, "&"); // Scope CSS variables
    scssSource = scssSource.replace(/body[\w:.\-()]*\.stnd-adapter/g, (match) => {
        return "&" + match.replace(/^body/, '').replace(/\.stnd-adapter/, '');
    });
    scssSource = scssSource.replace(/(?<![-_a-zA-Z0-9])body\b/g, "&");
    scssSource = scssSource.replace(/(?:^|\s|,)\.stnd-adapter([\w:.\-()]*)/g, (match, p1) => {
        const prefix = match.match(/^[ \s,]+/);
        const prefStr = prefix ? prefix[0] : "";
        return prefStr + "&" + p1;
    });

    const wrappedScss = `body.stnd-adapter {\n${scssSource}\n}`;

    let minifiedCss;
    try {
      const compiled = sass.compileString(wrappedScss, { style: "compressed" });
      minifiedCss = compiled.css;

      // Concaténer directement fonts.css pour éviter la lenteur de compilation SASS
      if (fs.existsSync(featuresDir)) {
        for (const feature of fs.readdirSync(featuresDir).sort()) {
          const fontsFile = path.join(featuresDir, feature, "fonts.css");
          if (fs.existsSync(fontsFile)) {
            minifiedCss += "\n" + fs.readFileSync(fontsFile, "utf8");
          }
        }
      }
    } catch (e) {
      console.error("SASS compilation failed:", e);
      process.exit(1);
    }

    // The native-only copy of the plugin's UI. Rules that are artisan-mode
    // refinements (they name .stnd-adapter) are left out of it.
    try {
      const nativeScss = uiCss
        .replace(/^\uFEFF/gm, "")
        .replace(/[^{}]*stnd-adapter[^{}]*\{[^{}]*\}/g, "");
      const nativeCss = sass.compileString(`body:not(.stnd-adapter) {\n${nativeScss}\n}`, { style: "compressed" }).css;
      minifiedCss += "\n" + nativeCss;
    } catch (e) {
      console.error("SASS compilation of the native UI styles failed:", e);
      process.exit(1);
    }

    // Compressed sass output starts with a U+FEFF byte-order mark as soon as it
    // holds a non-ASCII character. Obsidian injects styles.css as text, so the
    // mark glues itself to the first selector and the whole rule is dropped:
    // every token the design system sets under body.stnd-adapter vanished.
    minifiedCss = minifiedCss.replace(/\uFEFF/g, "");

    fs.writeFileSync(path.join(distDir, "styles.css"), minifiedCss);
    console.log(
      `Built dist/styles.css (${(minifiedCss.length / 1024) | 0}KB minified, themes lazy-loaded)`,
    );

    // ─── Deploy into the Obsidian vault ──────────────────────────────────────
    const vaultPlugins =
      process.env.VAULT_PLUGINS ||
      path.join(
        require("os").homedir(),
        "Documents",
        "Atelier",
        ".obsidian",
        "plugins",
      );
    const dest = path.join(vaultPlugins, "garden");
    if (fs.existsSync(vaultPlugins)) {
      if (!fs.existsSync(dest)) fs.mkdirSync(dest);
      fs.copyFileSync(
        path.join(distDir, "main.js"),
        path.join(dest, "main.js"),
      );
      fs.copyFileSync(
        path.join(distDir, "styles.css"),
        path.join(dest, "styles.css"),
      );
      fs.copyFileSync(
        path.join(__dirname, "manifest.json"),
        path.join(dest, "manifest.json"),
      );

      // Copy fonts recursively
      const copyDirSync = (src, target) => {
        if (!fs.existsSync(target)) fs.mkdirSync(target, { recursive: true });
        const entries = fs.readdirSync(src, { withFileTypes: true });
        for (const entry of entries) {
          const srcPath = path.join(src, entry.name);
          const destPath = path.join(target, entry.name);
          if (entry.isDirectory()) {
            copyDirSync(srcPath, destPath);
          } else {
            fs.copyFileSync(srcPath, destPath);
          }
        }
      };

      const distFonts = path.join(distDir, "fonts");
      if (fs.existsSync(distFonts)) {
        copyDirSync(distFonts, path.join(dest, "fonts"));
      }

      console.log(`Deployed to vault: ${dest}`);
    } else {
      console.log(
        "Vault not found — skipped deploy (set VAULT_PLUGINS to enable).",
      );
    }
  })
  .catch((err) => {
    console.error("Build failed:", err);
    process.exit(1);
  });
